# YUM install various package, might require EPEL repo prior to install
---
- hosts: "{{ hosts }}"
  #Privilege escalation
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: YUM install various EPEL packages
      yum: name=htop  state=present disable_gpg_check=yes update_cache=yes
...
